name: Image Template Remover
on:
  workflow_dispatch:
     inputs:
      Deploy Azure Bicep:
        description: 'Ù‹Deploy Azure Bicep Will be triggered'
        required: true
        default: 'Deploy Azure Bicep'
