on: [push]
name: Deploy Azure Bicep
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@main
    # Log into Azure
    - uses: azure/login@v1
      with:
        creds: ${{ secrets.CTCAZUREAVDMAGEBUILDERSPI }}
      # Deploy Bicep file
    - name: Deploy Bicep module
      uses: azure/CLI@v2
      with:
          azcliversion: 2.46.0        
          inlineScript: |
            az --version
            az deployment sub create --location 'westeurope' --template-file 'azureDeploy.bicep'' --parameters 'parameters.json' --verbose
            
