on: [push]
name: Deploy Azure Bicep
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@main
    # Log into Azure
    - uses: azure/login@v1
      with:
        creds: ${{ secrets.CTCAZUREAVDMAGEBUILDERSPI }}
      # Deploy Bicep file
    - name: deploy
      uses: azure/CLI@v1
      with:
        azcliversion: 2.23.0
         inlineScript:|
            az deployment group create --resource-group $resourceGroupName         
        subscriptionId: '54d81e17-d7a8-459c-9cca-ed176d923bb2'
        resourceGroupName: 'rg-avdaibautomated-prd-we-01'
        template: ./azureDeploy.bicep
        parameters: ./parameters.json
